### ISSUE TITLE
Segfault in test suite with 7.1.0

### ISSUE THREAD

**Issue by remicollet** [beberlei/env#7]
Build was OK, with RC2.

```
TEST 2/3 [tests/002.phpt]
========DIFF========
002+ 
003+ Termsig=11
========DONE========
FAIL env: Load simple INI file [tests/002.phpt] 

```

**Comment by remicollet** [comment]
```
(gdb) bt
#0  zend_mm_shutdown (heap=0x7ffff3800040, full=1, silent=<optimized out>) at /usr/src/debug/php-7.1.0/Zend/zend_alloc.c:2184
#1  0x000055555574691b in php_module_shutdown () at /usr/src/debug/php-7.1.0/main/main.c:2413
#2  0x000055555562118c in main (argc=62, argv=0x555555bc7600) at /usr/src/debug/php-7.1.0/sapi/cli/php_cli.c:1393

```
